import { WeekData } from "@/types";

export const weeks: WeekData[] = [
  {
    label: "Week 1: Curiosity & Observation",
    desc: "Opening his eyes to the world. Make him look, touch, and describe everything.",
    color: "#2196F3",
    days: [
      {
        num: 1, title: "Animal Intelligence", theme: "Science + Observation",
        objective: "Observation + Comparison + Expression",
        tags: ["Observation", "Movement", "Talking"],
        tools: ["📖 Animal Story Book", "🎨 Drawing Book", "✏️ Colored Pencils"],
        prep: {
          items: [
            "Keep a story book with animals ready (Panchatantra or any animal book)",
            "Keep drawing book and 5–6 colored pencils on the table",
            "Make a short mental list of 3–4 animals to act (tiger, rabbit, bird, elephant)",
            "Clear a small open area in the room for movement activity",
            "Think of 3–4 WHY questions about animals you'll ask him",
          ],
          mindset: "Your energy sets his energy. Come with curiosity, not a lesson plan. Be an explorer with him, not a teacher.",
        },
        steps: [
          { type: "HOOK", label: "Hook (Morning)", title: "Set the scene", say: "Today we are going to become animals. Not just play… we will think like animals." },
          { type: "ACTIVITY", label: "Active Learning (30 min)", title: "Act Like Animals", content: "Ask him to act physically:", say: "Show me how a tiger walks.\nNow how does a rabbit move?\nNow be a bird flying.", content2: "Let him move, jump, crawl. Don't stop him!" },
          { type: "THINK", label: "Guided Thinking (10 min)", title: "Deep Questions", qs: ["Why does a tiger walk slowly?", "Why does a rabbit jump fast?", "Why can birds fly but we cannot?"], hint: "If he struggles: Guide him → Tiger hunts so needs silence. Rabbit escapes so needs speed." },
          { type: "EXPRESS", label: "Expression (10 min)", title: "Make Him Explain", say: "Now explain to me: what is the difference between a tiger and a rabbit? Tell me everything." },
          { type: "CLOSE", label: "Reinforcement", title: "Close the loop", say: "Very good. You observed, you thought, and you explained. That is exactly how smart people learn." },
        ],
      },
      {
        num: 2, title: "Kitchen Science", theme: "Real World + Cause & Effect",
        objective: "Cause-Effect Understanding + Observation",
        tags: ["Science", "Real World", "Talking"],
        tools: ["🍳 Kitchen access", "🌾 Flour + Water", "📝 Notebook"],
        prep: {
          items: [
            "Keep small bowl, flour, and a cup of water on kitchen counter before he wakes up",
            "Think of 2 simple things to demonstrate: mixing water+flour, boiling water (you do the boiling, he observes)",
            "Keep a small notebook or paper for him to write/draw observations",
            "Plan which kitchen activity you'll show — pick the safest one for that morning",
            "Don't cook anything in advance — let the discovery happen with him",
          ],
          mindset: "Act excited. Say 'I wonder what happens if…' and mean it. His curiosity will match yours.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are not a child… you are a scientist working in the kitchen." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Kitchen Exploration", content: "Let him mix water + flour. Watch it change texture. Observe boiling water. Touch (safely) cold vs hot surfaces." },
          { type: "THINK", label: "Thinking Questions", title: "Guided Questions", qs: ["What happened when we added water?", "Why did it become soft?", "What happens when we heat it?", "Why does oil float on water?"] },
          { type: "EXPRESS", label: "Expression", title: "Chef Explanation", say: "Explain to me step by step how we made this. Pretend I don't know anything about cooking." },
          { type: "CLOSE", label: "Close", title: "Reinforcement", say: "You observed change happening. That is exactly what science is. Real scientists do exactly this." },
        ],
      },
      {
        num: 3, title: "Space Thinking", theme: "Imagination + Conceptual",
        objective: "Imagination + Big Thinking + Conceptual Understanding",
        tags: ["Space", "Role Play", "Thinking"],
        tools: ["📖 Space/Solar System Book", "🎨 Drawing Book", "🌍 Globe or ball"],
        prep: {
          items: [
            "If you have a globe or large ball, keep it ready to use as Sun",
            "Optionally browse 2–3 simple space images on phone to show him (planets, sun close-up)",
            "Clear space in the middle of the room for walking around (Earth orbiting Sun roleplay)",
            "Read a quick 2-min summary of solar system so you can guide him confidently",
            "Keep drawing book ready for him to draw the solar system after roleplay",
          ],
          mindset: "You don't need to know everything. It's okay to say 'I don't know — let's find out together.' That models curiosity.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we are going to space. You will be the Sun. I will be the Earth. Ready?" },
          { type: "ACTIVITY", label: "Role Play (30 min)", title: "Solar System Act", content: "He stands in center = Sun. You walk around him = Earth. Add Moon (sibling or toy). Walk slowly, discuss what each planet does." },
          { type: "THINK", label: "Thinking Questions", title: "Space Questions", qs: ["Why does Earth go around the Sun and not the other way?", "What happens if the Sun disappears suddenly?", "Why is it cold at night?", "How far do you think the Sun is?"] },
          { type: "EXPRESS", label: "Expression", title: "Space Reporter", say: "You are a news reporter on TV. Explain to everyone what the Sun does for us. Go!" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You understood something huge today. That's what scientists think about. You thought like one." },
        ],
      },
      {
        num: 4, title: "Nature Detectives", theme: "Attention to Detail",
        objective: "Observation + Comparison + Pattern Recognition",
        tags: ["Nature", "Outdoor", "Observation"],
        tools: ["🌿 Leaves from outside", "📏 Ruler", "🎨 Drawing paper", "🔍 Magnifying glass (if available)"],
        prep: {
          items: [
            "Identify a nearby area: garden, street, park — wherever leaves are accessible",
            "Keep a ruler and drawing paper on the table before starting",
            "Bring a small bag or envelope to collect leaves in",
            "If you have a magnifying glass anywhere in the house, find it the night before",
            "Make your own mini list: 3 differences you've noticed in leaves — just to guide him if he gets stuck",
          ],
          mindset: "Walk slowly. This is not exercise — it's observation. Let him set the pace of discovery.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we are detectives. Our case: find the differences in nature. Are you ready, Detective Manvay?" },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Leaf Hunt", content: "Go outside. Collect 5-8 different leaves. Compare size, shape, texture, colour. If possible, measure with ruler." },
          { type: "THINK", label: "Thinking Questions", title: "Detective Questions", qs: ["Which leaf is the biggest? Why do you think it grew so big?", "Why are they all different shapes?", "What would happen if all leaves were the same?", "Feel this leaf — why is it smooth/rough?"] },
          { type: "EXPRESS", label: "Expression", title: "Detective Report", say: "Give me your detective report. Tell me 5 differences you found in the leaves you collected." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You noticed things most people walk past every day. That attention — that's a superpower of intelligent people." },
        ],
      },
      {
        num: 5, title: "Engineer Day", theme: "Problem Solving + Building",
        objective: "Trial & Error + Problem Solving + Explanation",
        tags: ["Engineering", "Building", "Problem Solving"],
        tools: ["🛋️ Cushions / Pillows", "🧱 Blocks or LEGO", "📦 Cardboard boxes", "📏 Ruler"],
        prep: {
          items: [
            "Gather 4–6 cushions or pillows and place them in one spot",
            "Find any cardboard boxes (from groceries, Amazon, etc.) and flatten them nearby",
            "If LEGO or blocks are available, put them in a box ready to use",
            "Keep a ruler handy to test bridge/roof length",
            "Mentally decide the 'challenge brief': what should he build? (house, tower, bridge — pick one)",
          ],
          mindset: "Let it fall. Let it fail. Resist fixing it for him. Your patience during his frustration is the most important parenting skill today.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are the chief engineer. Your mission: build the strongest house possible using only these materials." },
          { type: "ACTIVITY", label: "Build (30 min)", title: "Build & Test", content: "Give him cushions, blocks, cardboard. Let him build freely for 15 min. Then test: push gently. Did it fall? Ask him to improve it." },
          { type: "THINK", label: "Thinking Questions", title: "Engineer Questions", qs: ["Why did this part fall?", "What can you change to make it stronger?", "Real buildings have a strong base — what does your base look like?", "If a storm came, which part would break first?"] },
          { type: "EXPRESS", label: "Expression", title: "Engineering Pitch", say: "Pretend I'm the client who wants to buy this house. Explain your design to me. Why is it strong?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You tried, it failed, you improved. That is exactly what real engineers do. That's called smart thinking." },
        ],
      },
      {
        num: 6, title: "Classification Master", theme: "Logic + Grouping",
        objective: "Logical Grouping + Reasoning + Pattern Thinking",
        tags: ["Logic", "Sorting", "Thinking"],
        tools: ["🧸 10 household objects", "📝 Paper + pen", "🎨 Colored stickers (optional)"],
        prep: {
          items: [
            "Tonight: collect exactly 10 different household objects and keep them in a bag/box",
            "Good objects: spoon, key, pen, rubber band, coin, bottle cap, eraser, leaf, button, clip",
            "Keep paper and pen ready on the table",
            "If you have colored stickers, keep them out — he can label the groups",
            "Think of 2–3 different ways the same objects can be sorted (by size, by material, by use)",
          ],
          mindset: "Accept all grouping logic — even if it seems wrong. First ask 'why did you group like this?' before suggesting a different way.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are a master sorter. Scientists sort things to understand them better. Let's see how YOU think." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Sort the Objects", content: "Place 10 different household objects on the floor. Ask him to group them. Accept any grouping — don't correct immediately. Then ask him to try another grouping." },
          { type: "THINK", label: "Thinking Questions", title: "Logic Questions", qs: ["Why did you put these together?", "Can you find a different way to group them?", "What do all these objects have in common?", "Which group was hardest to name?"] },
          { type: "EXPRESS", label: "Expression", title: "Explain Logic", say: "Explain your groups to me. For each group, tell me the rule you used to put them together." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You used logic to organize things. That's exactly how scientists, doctors, and computer programmers think." },
        ],
      },
      {
        num: 7, title: "Volcano Scientist", theme: "Science Experiment",
        objective: "Curiosity + Reaction Understanding + Scientific Expression",
        tags: ["Science", "Experiment", "Fun"],
        tools: ["🧪 Baking Soda (3 tbsp)", "🍶 Vinegar (½ cup)", "🍽️ Plate or bowl", "🎨 Red food colour (optional)", "📝 Paper for observations"],
        prep: {
          items: [
            "Tonight: check that you have baking soda and vinegar in your kitchen",
            "Keep a deep plate or bowl ready (to contain the fizz)",
            "Optional: keep red or orange food colour for volcano effect",
            "Prepare a small 'Scientist's Notebook' — just a folded paper works",
            "Keep extra baking soda and vinegar — you'll want to repeat the experiment 2–3 times",
            "Clear the kitchen counter for the experiment area",
          ],
          mindset: "Match his excitement. Gasp when the fizz happens. Your reaction gives him permission to be amazed. Science is about wonder first.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we will create a mini explosion in our kitchen. You are the lead scientist. Safety first — you are in charge." },
          { type: "ACTIVITY", label: "Experiment (30 min)", title: "Volcano Experiment", content: "Set up the plate. Let him pour baking soda. Add food colour. Ask him to predict what will happen. Then add vinegar. Watch the reaction. Do it 2-3 times." },
          { type: "THINK", label: "Thinking Questions", title: "Science Questions", qs: ["What did you see?", "Why did bubbles come?", "What happens if we add more baking soda?", "Is this the same as a real volcano? Why or why not?"] },
          { type: "EXPRESS", label: "Expression", title: "News Report", say: "You are a scientist on TV news. Explain to the whole country what just happened in this experiment. Make it exciting!" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You observed, predicted, tested, and explained. That is the complete scientific method. You did real science today." },
        ],
      },
    ],
  },
  {
    label: "Week 2: Thinking & Decision Making",
    desc: "Build logic, strategy, and deeper thinking. Push him to explain his decisions.",
    color: "#43A047",
    days: [
      {
        num: 8, title: "Chess Thinking", theme: "Strategy + Decision Reasoning",
        objective: "Forward Planning + Decision Justification",
        tags: ["Chess", "Strategy", "Logic"],
        tools: ["♟️ Chess Board", "📖 Chess beginners guide (optional)", "⏱️ Timer"],
        prep: {
          items: [
            "Set up the chess board the night before so it's ready on the table",
            "If he's never played, review the basic moves yourself: pawn and rook only for Day 1",
            "Write on a paper: pawn moves forward 1 (or 2 first move), rook moves straight",
            "Keep this cheat sheet next to the board for reference",
            "Plan to play very slowly — this is not about winning, it's about thinking aloud",
          ],
          mindset: "Don't play to win. Play to question. Every time he moves a piece, ask 'why?' before making your move.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are not just playing a game. You are planning battles. Every move must have a reason." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Chess Introduction", content: "Teach pawn and rook movements only. Play 1-2 very simple games. Focus on the thinking process, not winning." },
          { type: "THINK", label: "Thinking Questions", title: "Strategy Questions", qs: ["Why did you move THAT piece?", "What do you think will happen next?", "What is your plan for the next 2 moves?", "What would I do if you move there?"] },
          { type: "EXPRESS", label: "Expression", title: "Think Aloud", say: "Before each move, say out loud why you are moving there. Don't move silently — explain every decision." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You are learning to think ahead. That is one of the most powerful skills any person can have." },
        ],
      },
      {
        num: 9, title: "Puzzle Strategy", theme: "Problem-Solving Process",
        objective: "Systematic Thinking + Process Explanation",
        tags: ["Puzzle", "Focus", "Logic"],
        tools: ["🧩 Jigsaw Puzzle (100-200 pieces)", "⏱️ Timer", "📝 Paper to write strategy"],
        prep: {
          items: [
            "Open and mix the puzzle pieces the night before — don't sort them",
            "Keep a timer ready (phone timer works fine)",
            "Keep a pen and paper near the puzzle for him to write his strategy after",
            "Make sure the table has enough space — clear it completely",
            "If this is a puzzle he's done before, choose a harder one or flip the image to make it new",
          ],
          mindset: "Sit beside him, not across. Make him feel you're both solving it — even though you're just observing and asking questions.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today is a challenge. I want to see HOW your brain works, not just if you finish. Ready?" },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Timed Puzzle", content: "Set timer for 20 min. Let him solve. Note: where did he start? After first attempt, mix and try again asking him to use a different strategy." },
          { type: "THINK", label: "Thinking Questions", title: "Process Questions", qs: ["Where did you start — why that spot?", "What did you look for first?", "When you got stuck, what did you do?", "How would you do it faster next time?"] },
          { type: "EXPRESS", label: "Expression", title: "Explain Your Method", say: "Teach me your puzzle strategy. If your friend had never done a puzzle, what steps would you tell them?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "Smart people don't rush. They observe, plan, then act. You did that today." },
        ],
      },
      {
        num: 10, title: "Story Decision", theme: "Decision Making + Creativity",
        objective: "Decision-Making + Creative Thinking + Narrative Skills",
        tags: ["Storytelling", "Creativity", "Decisions"],
        tools: ["📖 Panchatantra or any story book", "🎨 Drawing paper", "✏️ Pencils"],
        prep: {
          items: [
            "Choose the story the night before — read it yourself first (5 min)",
            "Pick a story with a clear decision moment (a character choosing between two paths)",
            "Prepare 2 alternate ending ideas in your mind — to suggest if he gets stuck",
            "Keep drawing paper and pencils ready for him to draw his new ending",
            "Bookmark the page so you go straight to reading without delay",
          ],
          mindset: "Don't correct his alternate ending — no ending is wrong. The goal is that he made a decision and can explain why.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are the author. We will read a story, and then YOU will change the ending. You are in charge." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Read + Reimagine", content: "Read 1 complete story. Discuss what happened. Then ask him to create 2 different alternate endings. He draws the new ending scene." },
          { type: "THINK", label: "Thinking Questions", title: "Story Questions", qs: ["Why did the character make that choice?", "What would YOU have done differently?", "In your new ending — why is it better?", "What did the character learn? What did YOU learn?"] },
          { type: "EXPRESS", label: "Expression", title: "Tell Your Version", say: "Tell me your new story from the beginning. Make it exciting — I want to feel like I'm inside it." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You made decisions for a character. That is how writers, directors, and leaders think." },
        ],
      },
      {
        num: 11, title: "Bridge Engineering", theme: "Trial-Error Learning",
        objective: "Problem Solving + Improvement Mindset + Explanation",
        tags: ["Engineering", "Testing", "Improvement"],
        tools: ["📄 Paper (10+ sheets)", "📏 Ruler", "🖇️ Tape", "📚 Books to test weight"],
        prep: {
          items: [
            "Keep 15–20 sheets of plain paper in a pile (old newspaper works too)",
            "Find a roll of tape and keep it accessible",
            "Stack 4–5 small books nearby for weight testing",
            "Keep a ruler for measuring span",
            "Set up the 'bridge site': two stacks of books or two chairs as bridge supports",
            "Draw a simple challenge on paper: 'Bridge must span this gap and hold books'",
          ],
          mindset: "The bridge will fall. That is the point. Control your urge to help. Your calm reaction to failure teaches him that failure is just data.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "You are an engineer. Your mission: build a bridge from paper that can hold as many books as possible." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Build + Test + Improve", content: "Give paper and tape only. Let him build for 15 min. Test with 1 book, then 2, then more. When it breaks — improve. At least 2 rounds of building." },
          { type: "THINK", label: "Thinking Questions", title: "Engineer Questions", qs: ["Why did it break at that point?", "What can you change to make it stronger?", "Real bridges have special shapes — which shapes are strongest?", "What would you do differently if you had one more chance?"] },
          { type: "EXPRESS", label: "Expression", title: "Engineering Report", say: "Explain your bridge design. What is your strongest version? How many books did it hold? What would Version 3 look like?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "Failure + improvement = engineering. Every bridge in the world was built using exactly this process." },
        ],
      },
      {
        num: 12, title: "Pattern Thinking", theme: "Logical Recognition",
        objective: "Pattern Recognition + Rule Discovery + Logic",
        tags: ["Patterns", "Logic", "Math Thinking"],
        tools: ["🔵🔴 Colored objects (blocks, coins, buttons)", "📝 Paper", "✏️ Pencil"],
        prep: {
          items: [
            "Collect 15–20 small objects in 2–3 colors: coins, buttons, blocks, or bottle caps",
            "Sort them into groups by color the night before so you can quickly make patterns",
            "Keep paper and pencil ready for him to draw his own patterns",
            "Prepare 3 patterns in your head: easy → medium → hard (e.g., AB, ABB, AABB)",
            "Think of 1 real-world pattern to show him: tiles on floor, windows on a building",
          ],
          mindset: "Start easy — let him feel confident. Then make it harder gradually. Confidence first, challenge second.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we will find hidden rules in patterns. The smartest minds in math and science are pattern finders." },
          { type: "ACTIVITY", label: "Activity (25 min)", title: "Create + Discover Patterns", content: "You make a pattern with objects (red, blue, red, blue...). Ask him what comes next. Then make harder patterns. Then let HIM create patterns for you to guess." },
          { type: "THINK", label: "Thinking Questions", title: "Pattern Questions", qs: ["What comes next — how do you know?", "What is the rule in this pattern?", "Can you make a pattern with 3 colors?", "What patterns do you see in our house or outside?"] },
          { type: "EXPRESS", label: "Expression", title: "Explain the Rule", say: "Create your own pattern. Then explain the rule to me as if you're teaching a class. Be the teacher!" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You discovered hidden rules. That is exactly what mathematicians and scientists do every day." },
        ],
      },
      {
        num: 13, title: "WHY Master Day", theme: "Deep Curiosity",
        objective: "Questioning + Deep Curiosity + Critical Thinking",
        tags: ["Curiosity", "WHY Questions", "Deep Thinking"],
        tools: ["📖 365 Why Questions Book (optional)", "📝 Notebook", "✏️ Pen"],
        prep: {
          items: [
            "Keep a dedicated notebook for WHY Day — this becomes his 'Question Journal'",
            "Write today's date on the first page the night before",
            "Prepare 5 backup WHY questions in case he runs out of ideas",
            "Have your phone ready to look up answers together when neither of you knows",
            "Optional: write '❓ WHY MASTER DAY' on top of a page to make it feel special",
          ],
          mindset: "There are no silly questions today. Respond to every WHY with genuine curiosity, even if you know the answer. Say 'What do YOU think first?'",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today is special. Today, YOU are the questioner. You can ask me ANY why question. I will try to answer. If I don't know — we find out together." },
          { type: "ACTIVITY", label: "Activity (35 min)", title: "WHY Question Game", content: "He asks 10-15 WHY questions freely. Write them down. For each, discuss together. Look up answers together. This is a 2-way conversation." },
          { type: "THINK", label: "Guided Questions from You", title: "Prompt Ideas If He Gets Stuck", qs: ["Why does the sky change colour at sunset?", "Why do we dream at night?", "Why do some animals live in water?", "Why do we need to eat every day?", "Why is glass transparent?"] },
          { type: "EXPRESS", label: "Expression", title: "Favourite WHY", say: "Which WHY question was your favourite today? Tell me what the answer was in your own words." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "The greatest scientists — Einstein, Newton — they asked WHY about everything. Today, you were one of them." },
        ],
      },
      {
        num: 14, title: "Plant Life Project", theme: "Observation Over Time",
        objective: "Long-Term Observation + Scientific Prediction + Care",
        tags: ["Science", "Nature", "Long-term Project"],
        tools: ["🌱 Seeds (methi or beans)", "🪴 Small pot or cup", "🌍 Soil", "💧 Water", "📝 Observation diary"],
        prep: {
          items: [
            "Buy or find seeds: methi (fenugreek), moong, or any bean — these sprout fast in 3–5 days",
            "Find a small pot, cup, or even a cut plastic bottle as planter",
            "Arrange soil — garden soil or a small bag from a local nursery (₹20)",
            "Make an 'Observation Diary': staple 10 pages together and write Day 1 to Day 14 on each page",
            "Pick a sunny spot near a window where the pot will live — identify this the night before",
            "Keep a small watering cup or spoon ready",
          ],
          mindset: "This is a 2-week commitment. Water it with him every morning. His consistency with the plant = your consistency with the program.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you will start something that will grow over many days. You will grow life. This is a real science project." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Plant the Seed", content: "Prepare the pot with soil together. Let him place the seeds. Water carefully. He writes Day 1 in his observation diary." },
          { type: "THINK", label: "Thinking Questions", title: "Life Questions", qs: ["What does this seed need to grow?", "What do YOU think it will look like in 7 days?", "What will happen if we forget to water it?", "Why do plants need sunlight?"] },
          { type: "EXPRESS", label: "Expression", title: "Scientist's Prediction", say: "Write your prediction in your diary. Describe exactly what you think will happen in the next 14 days. Be specific!" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You have started a long-term project. Great scientists are patient observers. Check it every day. Write what you see." },
        ],
      },
    ],
  },
  {
    label: "Week 3: Creativity & Expression",
    desc: "Channel his talkative energy into storytelling, presentation, and creative invention.",
    color: "#FF8C42",
    days: [
      {
        num: 15, title: "Superhero Creator", theme: "Creative Design + Storytelling",
        objective: "Imagination + Character Design + Expressive Storytelling",
        tags: ["Creativity", "Storytelling", "Drawing"],
        tools: ["🎨 Drawing book", "✏️ Colored pencils", "📝 Character design sheet"],
        prep: {
          items: [
            "Keep the drawing book open to a fresh page on the table",
            "Sharpen all colored pencils the night before",
            "Draw a simple 'Character Sheet' template on paper: boxes for Name, Power, Weakness, City, Enemy",
            "Optional: show him 1–2 superhero characters briefly (just an image) for inspiration",
            "Think of 3 unique superpower ideas to suggest only if he gets completely stuck",
          ],
          mindset: "Do not suggest your favourite superhero as a starting point — let his imagination come first. Ask 'What problem in the world would you want to fix?' to inspire the character.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are a superhero designer. You will create the most unique hero the world has ever seen." },
          { type: "ACTIVITY", label: "Activity (35 min)", title: "Design + Act", content: "Draw the superhero (15 min). Name them. Define: powers, weaknesses, mission, enemy, home city. Then ACT as that hero — move like them, speak like them." },
          { type: "THINK", label: "Thinking Questions", title: "Design Questions", qs: ["Why did you choose those specific powers?", "What is your hero's weakness — why does every hero need one?", "Who is the villain — why are they the villain?", "What problem does your hero solve in the world?"] },
          { type: "EXPRESS", label: "Expression", title: "Hero Pitch", say: "Pitch your superhero to me like you're presenting to a comic book company. Name, powers, mission, and why the world needs this hero." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You created something completely new. Every story, movie, and book starts exactly like this — from imagination." },
        ],
      },
      {
        num: 16, title: "City Builder", theme: "Design + Systems Thinking",
        objective: "Spatial Thinking + Systems Design + Explanation",
        tags: ["Building", "Design", "Creativity"],
        tools: ["🧱 LEGO / Blocks", "📦 Small boxes", "🖊️ Paper for city map", "🏠 Toy figures (optional)"],
        prep: {
          items: [
            "Gather ALL building materials the night before: LEGO, blocks, empty boxes, toilet rolls, small containers",
            "Find small toy figures or cut out paper people to act as city residents",
            "Draw a simple blank city map grid on A4 paper (just squares like a top-view map)",
            "Clear a large flat surface — floor works better than table for a city build",
            "Think of the 'must-have' city elements to prompt him if he forgets: hospital, school, park, roads",
          ],
          mindset: "Let him be the mayor. Don't suggest where things should go. Ask questions, don't give answers. 'Where will the people get water from?' works better than 'You should add a water tank.'",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are the mayor and chief architect. Build me a city. It needs everything a real city has." },
          { type: "ACTIVITY", label: "Activity (40 min)", title: "Build the City", content: "Plan the city on paper first (5 min). Build using blocks and boxes (25 min). Must include: homes, hospital, park, shops, road." },
          { type: "THINK", label: "Thinking Questions", title: "City Planning Questions", qs: ["Why did you put the hospital there?", "Where does the water come from in your city?", "What happens if a big storm hits your city?", "What is missing that your city still needs?"] },
          { type: "EXPRESS", label: "Expression", title: "City Tour Guide", say: "I am a visitor coming to your city for the first time. Give me a tour. Tell me about every area and why it was built there." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You designed a system. Cities are systems. Bodies are systems. Technology is systems. You think like a systems designer." },
        ],
      },
      {
        num: 17, title: "Teacher Role Day", theme: "Deep Understanding Through Teaching",
        objective: "Comprehension + Confidence + Communication",
        tags: ["Teaching", "Communication", "Confidence"],
        tools: ["📝 Small whiteboard or paper", "✏️ Marker", "📖 Any topic he knows"],
        prep: {
          items: [
            "Ask him the night before: 'Tomorrow you will teach me something — what topic do you want to teach?'",
            "Keep paper or whiteboard + markers ready on the table",
            "If he chose a topic, lightly read about it so you can ask good 'student questions'",
            "Prepare 4–5 genuine-sounding student questions: 'But why?', 'Can you show me?', 'I don't understand that part'",
            "Make a simple 'Student Badge' for yourself and a 'Teacher Badge' for him (just paper + tape) to make it fun",
          ],
          mindset: "Be a genuinely curious student. Look confused when appropriate. Ask questions a 7-year-old might ask another child. This builds his confidence, not your convenience.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today the roles are completely reversed. You are the teacher. I am the student. Teach me something. Anything you know." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "He Teaches You", content: "Let him pick ANY topic. Give him a whiteboard or paper. He must teach for at least 10 minutes. Ask 'student questions' that challenge him." },
          { type: "THINK", label: "Student Questions You Ask", title: "Ask These as a 'Student'", qs: ["But WHY does that happen?", "I don't understand that part — can you explain differently?", "What is the most important thing I should remember?", "Can you show me an example?"] },
          { type: "EXPRESS", label: "Expression", title: "Teaching IS Expression", say: "Now summarize your lesson in 5 sentences. What are the 5 most important things you taught me today?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "If you can teach it, you truly understand it. Today you proved you understand deeply. That is real intelligence." },
        ],
      },
      {
        num: 18, title: "Art + Story", theme: "Visual Storytelling",
        objective: "Creative Expression + Narrative + Emotional Storytelling",
        tags: ["Art", "Story", "Creativity"],
        tools: ["🎨 Drawing book + colors", "✏️ Pencils", "🖌️ Watercolors (if available)"],
        prep: {
          items: [
            "Draw a simple 4-box comic strip template on paper (2x2 grid with thick borders)",
            "Make 3 copies of the template — one practice, two final",
            "Keep all colors, pencils, and watercolors accessible in one place",
            "If you have watercolors, test them the night before to check they still work",
            "Think of a gentle story prompt in case he needs a starting idea: 'A boy who could talk to animals'",
          ],
          mindset: "Do not correct the drawings — stick figures are perfect. You are not building an artist, you are building a storyteller. The story matters more than the art quality.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you will tell a story — but not with words. First, you draw it. Then you tell it." },
          { type: "ACTIVITY", label: "Activity (35 min)", title: "Draw a Story", content: "Ask him to draw a 4-frame story (like a comic strip). Each box = one part of the story. No words needed. Characters, setting, problem, solution." },
          { type: "THINK", label: "Thinking Questions", title: "Story Craft Questions", qs: ["Who is the main character — what are they feeling?", "What is the problem in your story?", "How does the character change from beginning to end?", "Why did you choose these colors for this scene?"] },
          { type: "EXPRESS", label: "Expression", title: "Narrate the Story", say: "Now narrate your story to me as if it's an animated movie. Use different voices for different characters. Make it come alive!" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You connected pictures and words into a complete story. Authors, filmmakers, and game designers work exactly this way." },
        ],
      },
      {
        num: 19, title: "Rhythm & Memory", theme: "Auditory Memory + Pattern",
        objective: "Auditory Memory + Focus + Pattern Tracking",
        tags: ["Memory", "Rhythm", "Focus"],
        tools: ["👐 Hands for clapping", "🥄 Spoon + table for rhythm", "📝 Paper to draw rhythm patterns"],
        prep: {
          items: [
            "Practice 5 rhythm patterns yourself the night before: start simple, end complex",
            "Pattern examples: clap-clap-pause, clap-clap-stomp, clap-stomp-clap-pause-clap",
            "Keep a spoon and a table surface ready as a drum",
            "Draw rhythm patterns on paper using symbols: ● for clap, ✦ for stomp, — for pause",
            "Clear the room of distractions — this activity needs focused listening",
          ],
          mindset: "This is a listening and memory exercise. Keep the room quiet. Your calm, focused energy will help him concentrate. Do it like a game, not a drill.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we train the memory inside your ears. This is how musicians, dancers, and mathematicians train their brains." },
          { type: "ACTIVITY", label: "Activity (25 min)", title: "Copy My Rhythm", content: "Clap a simple pattern. He copies. Make it harder each round. Then switch — he creates, you copy. Try body percussion: clap, stomp, tap. Progress to 8-beat patterns." },
          { type: "THINK", label: "Thinking Questions", title: "Memory Questions", qs: ["How did you remember that long pattern?", "What happened in your head when you heard it?", "Which pattern was hardest — why?", "Where do you hear rhythms in everyday life?"] },
          { type: "EXPRESS", label: "Expression", title: "Explain the Method", say: "How do you memorize a rhythm? Explain your strategy to me. What tricks did you use?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You trained your memory today. The same skill you used for rhythm — you can use for languages, numbers, and names." },
        ],
      },
      {
        num: 20, title: "Invention Day", theme: "Design Thinking + Problem Solving",
        objective: "Creative Problem Solving + Design Thinking + Pitching",
        tags: ["Invention", "Creativity", "Problem Solving"],
        tools: ["♻️ Waste materials (boxes, bottles, paper rolls, rubber bands)", "🖇️ Tape + glue", "✂️ Scissors (supervised)"],
        prep: {
          items: [
            "Collect waste materials the night before: cardboard tubes, plastic bottles, rubber bands, bottle caps, old cloth, boxes",
            "Keep them in one big box labelled 'Invention Materials'",
            "Set out tape, glue stick, and scissors (you'll supervise the scissors)",
            "Think of 3 real small problems at home that he might want to solve: pencils rolling, bag falling, toys scattered",
            "Prepare a '2-minute pitch' template on paper: Problem / My Solution / Who It Helps / What I Used",
          ],
          mindset: "The invention doesn't need to work perfectly. What matters is he identified a problem and designed a solution. Celebrate the thinking, not the result.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are an inventor. Real inventors see a problem and create a solution from whatever they have. Your materials: ONLY waste from our home." },
          { type: "ACTIVITY", label: "Activity (40 min)", title: "Invent Something Useful", content: "First 5 min: he identifies ONE problem to solve. Then 30 min: build the solution from waste materials. No buying anything." },
          { type: "THINK", label: "Thinking Questions", title: "Inventor Questions", qs: ["What problem exactly are you solving?", "Who would use this invention?", "How did you decide to use THAT material for THAT part?", "What would make it even better?"] },
          { type: "EXPRESS", label: "Expression", title: "Pitch the Invention", say: "Pretend I am an investor with ₹1 crore. Pitch your invention to me in 2 minutes. Tell me the problem, your solution, and why I should invest." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You saw a problem, designed a solution, and built it. That is entrepreneurship. The world's biggest companies started exactly this way." },
        ],
      },
      {
        num: 21, title: "Presentation Day", theme: "Confidence + Communication",
        objective: "Public Speaking + Confidence + Organization",
        tags: ["Presentation", "Confidence", "Communication"],
        tools: ["🎤 Pretend microphone (any object)", "📝 Notes paper", "👨‍👩‍👦 Full family audience"],
        prep: {
          items: [
            "Inform family members the night before: 'Tomorrow Manvay has a presentation — please be available for 15 minutes'",
            "Make or find a pretend microphone — a TV remote, a rolled paper, anything cylindrical",
            "Set up chairs in a small row like an audience — do this before he wakes up so he sees the setup",
            "Keep his best creations from the week in one place for him to choose from",
            "Prepare a simple 'Certificate of Presentation' to give him after (just write it by hand on paper)",
          ],
          mindset: "You are the proud audience, not the judge. Clap genuinely. Ask 1 kind question after. Make it feel like a real, important event — because for him, it is.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today is your big day. We have a special audience — the whole family. You will present your BEST creation from this week." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Prepare + Present", content: "Give 15 min to prepare. He chooses his best work. He plans what to say. Family sits as audience. He presents for 5-10 minutes." },
          { type: "THINK", label: "Thinking Questions", title: "Presenter Questions", qs: ["Why did you choose THIS as your best work?", "What are you most proud of in this creation?", "What would you improve if you had more time?", "What did you learn while making this?"] },
          { type: "EXPRESS", label: "Expression", title: "The Presentation Itself", say: "Now present! Remember: speak slowly, make eye contact, and be proud of what you made." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You stood up, spoke clearly, and shared your work with confidence. That is what leaders, teachers, and entrepreneurs do every day." },
        ],
      },
    ],
  },
  {
    label: "Week 4: Real-World Intelligence",
    desc: "Apply all learning to real-life situations — money, empathy, planning, and decision making.",
    color: "#FF6B6B",
    days: [
      {
        num: 22, title: "Money Manager", theme: "Financial Thinking + Decision Making",
        objective: "Decision-Making + Value Understanding + Explanation",
        tags: ["Money", "Decisions", "Real Life"],
        tools: ["💰 ₹50 in coins", "📝 Paper to list options", "🛒 A small shop nearby (optional)"],
        prep: {
          items: [
            "Keep ₹50 ready in coins or small notes — physical money makes it more real for him",
            "Write a simple 'Decision Sheet' on paper with 3 blank boxes: Option 1, Option 2, Option 3, and 'I Choose'",
            "If going to a shop, identify a nearby kirana or stationery shop within walking distance",
            "Think of the approximate prices of things he might want: biscuits, pencil, small toy, snack",
            "Mentally prepare yourself: do not guide his spending choice — this is his decision fully",
          ],
          mindset: "Whatever he buys — even if it seems wasteful — is the right choice today. The goal is the decision process, not the outcome. Don't interfere.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are in charge of money. This is REAL money. ₹50 — yours to spend. But before you spend, you must plan." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "The Money Challenge", content: "Give him ₹50. Ask him to write 3 things he COULD buy. Pick one. Go buy it (or simulate at home). Discuss: was it worth it? What did he give up?" },
          { type: "THINK", label: "Thinking Questions", title: "Money Questions", qs: ["Why did you choose this over the others?", "What did you give up by choosing this?", "If you had ₹100, what would you do differently?", "Why are some things more expensive than others?"] },
          { type: "EXPRESS", label: "Expression", title: "Explain the Decision", say: "Tell me your full decision process. What did you think about before spending? Would you make the same choice again?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "Every decision has a trade-off. You just learned the #1 rule of economics — used by businessmen, governments, and families worldwide." },
        ],
      },
      {
        num: 23, title: "Chef Day", theme: "Sequencing + Real Skills",
        objective: "Sequential Thinking + Real-World Skills + Explanation",
        tags: ["Cooking", "Life Skills", "Sequencing"],
        tools: ["🍳 Kitchen access", "🥪 Simple recipe ingredients", "📝 Recipe paper", "⏱️ Timer"],
        prep: {
          items: [
            "Decide the dish the night before — best options: sandwich, fruit salad, lemonade, or boiled noodles",
            "Buy or confirm all ingredients are available at home",
            "Write the recipe steps on paper so he has it as a reference while cooking",
            "Clear the kitchen counter and set out ingredients before he wakes up",
            "Keep a small apron or cloth ready for him to wear — it builds the 'chef identity'",
            "Supervise safety: fire, knives, and hot water are your responsibility, everything else is his",
          ],
          mindset: "Step back physically. Let him struggle with the sequence. If he does a step out of order, ask 'Does that feel right?' — don't tell him it's wrong.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are the head chef of our kitchen. You will make something completely by yourself. I am only your assistant." },
          { type: "ACTIVITY", label: "Activity (40 min)", title: "Cook Something Simple", content: "Suggestions: Sandwich with toppings, Fruit salad, Boiled egg (supervised), Lemonade. He does the work, you supervise safety." },
          { type: "THINK", label: "Thinking Questions", title: "Chef Questions", qs: ["Why do we do steps in this order?", "What would happen if we skipped a step?", "How do we know when it's ready?", "What would make this dish even better?"] },
          { type: "EXPRESS", label: "Expression", title: "Recipe Explanation", say: "Explain this recipe to me as if I've never cooked before. Step by step, with exact instructions. I'm going to try making it from your instructions alone." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You followed a process, adapted when needed, and created something real. That is project management — the most valuable workplace skill." },
        ],
      },
      {
        num: 24, title: "Market Explorer", theme: "Real-World Observation",
        objective: "Observation + Value Understanding + Economic Thinking",
        tags: ["Market", "Real World", "Observation"],
        tools: ["🛍️ A visit to local market or kirana store", "📝 Notebook", "✏️ Pen"],
        prep: {
          items: [
            "Identify the market you'll visit — ideally a local sabzi market or kirana, not a mall",
            "Keep a small notebook and pen in your bag for him to write or draw observations",
            "Plan to go in the morning when the market is active",
            "Mentally prepare 3 observation tasks for him: find the most expensive item, find the cheapest, watch how a shopkeeper talks",
            "Keep ₹20 extra in case he wants to buy one small thing he observes",
          ],
          mindset: "Walk slowly. Let him lead. Point at things and ask 'What do you notice?' rather than explaining. A child who observes a market for one hour learns more economics than a textbook chapter.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are an undercover reporter. We are going to the market. Your mission: observe everything and understand how buying and selling works." },
          { type: "ACTIVITY", label: "Activity (40 min)", title: "Market Investigation", content: "Visit a local market or shop. He notes: 3 things that are expensive + why. 3 things that are cheap + why. How does the shopkeeper talk to customers?" },
          { type: "THINK", label: "Thinking Questions", title: "Market Questions", qs: ["Why does this cost more than that?", "Why do people choose the cheaper one sometimes?", "How does the shopkeeper make money?", "If YOU had a shop, what would you sell and why?"] },
          { type: "EXPRESS", label: "Expression", title: "Market Report", say: "You are a TV reporter. Tell me your top 3 observations from the market today. What surprised you the most?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You just observed economics happening in real life. Every business idea starts with exactly this kind of observation." },
        ],
      },
      {
        num: 25, title: "Safety Thinking", theme: "Problem Solving + Safety",
        objective: "Critical Thinking + Safety Awareness + Decision Under Pressure",
        tags: ["Safety", "Problem Solving", "Role Play"],
        tools: ["🎭 Role play setup", "📝 Paper to write plan", "📱 Discuss phone usage in emergency"],
        prep: {
          items: [
            "Write down your home address clearly on a card for him to memorize",
            "Make sure he knows at least one phone number by heart — rehearse this the night before",
            "Prepare 3 role-play scenarios on paper with short descriptions",
            "Think about the 2–3 trusted adults in your area he can go to if lost",
            "Keep paper and pen for him to write his 'Safety Plan' at the end of the session",
          ],
          mindset: "Keep the tone calm and practical — not scary. Frame it as 'Smart preparation, not danger.' He should feel more confident after this session, not more fearful.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we practice for situations that we hope never happen. But being prepared makes you safe and smart. Ready?" },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Emergency Role Plays", content: "Scenario 1: You get separated from Amma at the market. Scenario 2: You fall down and get hurt when alone. Scenario 3: A stranger offers you something. Role play all 3 with him taking the lead." },
          { type: "THINK", label: "Thinking Questions", title: "Safety Questions", qs: ["Who is the safest person to ask for help?", "What are 3 things you should NEVER do with strangers?", "What information must you always know by heart?", "How do you stay calm when scared?"] },
          { type: "EXPRESS", label: "Expression", title: "Safety Plan", say: "Tell me YOUR safety plan if you ever got separated from us. I want to hear exactly what you would do, step by step." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You have a plan now. Brave people aren't those who feel no fear. They are those who have thought ahead and are prepared." },
        ],
      },
      {
        num: 26, title: "Emotional Intelligence", theme: "Empathy + Social Thinking",
        objective: "Empathy + Emotional Understanding + Social Intelligence",
        tags: ["Empathy", "Emotions", "Social Skills"],
        tools: ["🎭 Role play scenarios (written on chits)", "🎨 Emotion face cards (draw 6 faces)", "📝 Notebook", "🧻 Tissues (just in case)"],
        prep: {
          items: [
            "Draw 6 simple emotion faces on paper: happy, sad, angry, scared, confused, excited — label each",
            "Write 3 role-play scenarios on separate paper chits",
            "Think of a real situation from his life (a fight with a friend, a disappointment) you can gently reference",
            "Prepare to share one of your own emotional experiences as an example — kids learn empathy by seeing parents model it",
            "Keep tissues nearby just in case — emotional conversations can sometimes bring up real feelings",
          ],
          mindset: "If he becomes quiet or emotional, that is good — it means he is connecting. Don't rush past it. Sit with the feeling for a moment before moving on.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we will learn something more powerful than any school subject: understanding feelings — yours and others'." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Emotion Role Plays", content: "Scenario 1: Your best friend is crying and won't tell you why. What do you do? Scenario 2: You are very angry at someone. How do you handle it? Scenario 3: You did something wrong and hurt a friend. Role play the apology." },
          { type: "THINK", label: "Thinking Questions", title: "Empathy Questions", qs: ["How do you think your friend is feeling right now?", "What do people need when they are sad?", "When YOU are angry, what helps you feel better?", "Why is it important to say sorry even when it's hard?"] },
          { type: "EXPRESS", label: "Expression", title: "Feelings Explanation", say: "Tell me about a time you felt very sad or angry. What happened? What helped? What would you do differently now?" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "Understanding feelings — yours and others' — is the highest form of intelligence. Leaders, doctors, and good friends all have this." },
        ],
      },
      {
        num: 27, title: "Time Planner", theme: "Self-Management + Planning",
        objective: "Self-Management + Priority Thinking + Ownership",
        tags: ["Planning", "Time", "Responsibility"],
        tools: ["📝 Paper", "✏️ Pen", "⏰ Clock/Watch for reference", "📅 Schedule template"],
        prep: {
          items: [
            "Draw a schedule template the night before: two columns — Time and Activity, rows for every hour 8am–8pm",
            "Make 2 copies so he can revise if needed",
            "Keep a clock or watch visible in the room so he can reference actual time",
            "List on a chit: things that must be in his schedule today (meals, outdoor play, reading)",
            "Let him know the night before: 'Tomorrow you will plan your own day from morning to night!'",
          ],
          mindset: "Follow his plan as closely as possible for the rest of the day. If it's impractical, ask 'Is that enough time for that?' — but ultimately respect his choices. This teaches real consequences of planning decisions.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today you are the boss. You will plan your own entire day. I won't tell you what to do. You decide everything." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Plan Your Day", content: "Give paper + pen. He creates his schedule from 8am to 8pm. Must include: activities, meals, play, learning, and sleep time. He then follows his plan for the rest of the day." },
          { type: "THINK", label: "Thinking Questions", title: "Planning Questions", qs: ["Why did you put outdoor play THERE specifically?", "Is there enough time for everything?", "What happens if one activity takes longer?", "What is the most important thing in your schedule?"] },
          { type: "EXPRESS", label: "Expression", title: "Present the Plan", say: "Present your schedule to me. Explain every time slot and WHY you chose to put each activity at that time." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You planned your own day. That is self-management — the skill that separates highly successful people from everyone else." },
        ],
      },
      {
        num: 28, title: "Mini Debate", theme: "Critical Thinking + Argumentation",
        objective: "Argumentation + Critical Thinking + Confidence Under Challenge",
        tags: ["Debate", "Thinking", "Confidence"],
        tools: ["📝 Paper to note points", "⏱️ Timer (2 min per side)", "🎤 Pretend microphone"],
        prep: {
          items: [
            "Write 3 debate topics on separate chits — let him pick one randomly from a box",
            "Set a timer on your phone for 2-minute prep rounds",
            "Keep a pretend microphone ready (rolled paper or remote)",
            "Prepare to argue the OPPOSITE side of whatever he picks — think of 3 strong points in advance",
            "Draw a simple 'Debate Score Sheet' on paper: Clarity, Arguments, Examples, Confidence — just for fun rating",
          ],
          mindset: "Argue back genuinely — don't let him win too easily. The productive challenge of being questioned and having to defend his position is the entire point of this exercise.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today we have a debate. I will give you a topic. You will argue ONE side — even if you disagree with it. The goal is to think and argue clearly." },
          { type: "ACTIVITY", label: "Activity (30 min)", title: "Debate Topics", content: "Topic 1: Is mobile phone good or bad? Topic 2: Is it better to have fewer friends or many friends? Topic 3: Should children choose what to study, or should parents decide? He picks a side. 2 min to prepare. 3 min to argue." },
          { type: "THINK", label: "Thinking Questions", title: "Debate Questions", qs: ["What is your strongest point?", "What would the OTHER side say to challenge you?", "How would you answer that challenge?", "Did your opinion change after hearing both sides?"] },
          { type: "EXPRESS", label: "Expression", title: "The Debate Itself", say: "Present your argument. Speak clearly. Use examples. Don't repeat the same point. Try to convince me!" },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You argued your position with evidence and examples. Lawyers, politicians, business leaders — this is exactly what they do every single day." },
        ],
      },
    ],
  },
  {
    label: "Final 2 Days: Integration & Celebration",
    desc: "Bring everything together. Reflect, celebrate, and solidify all the growth.",
    color: "#845EC2",
    days: [
      {
        num: 29, title: "Ultimate Challenge", theme: "All Skills Combined",
        objective: "Integration of All Learned Skills",
        tags: ["All Skills", "Challenge", "Integration"],
        tools: ["🧩 Puzzle", "📖 Story Book", "🎨 Drawing book", "🎤 Microphone", "♟️ Chess Board"],
        prep: {
          items: [
            "Set up ALL stations the night before in different corners of the room: puzzle on one table, chess on another, book on sofa, drawing supplies ready",
            "Write a 'Champion Challenge Card' — list all 5 tasks with checkboxes",
            "Keep the timer ready — each station is 10 minutes",
            "Inform family to be available for the 1-minute speech at the end",
            "Make sure the plant is watered and visible — it's part of Day 29's reflection",
          ],
          mindset: "This is his Olympics. Bring the energy. Say 'This is your day, Champion.' Make it feel like the finale it is. Your pride and presence is his biggest reward.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "This is your final challenge. Today you will use EVERYTHING you have learned in the past 29 days. Are you ready, Champion?" },
          { type: "ACTIVITY", label: "Activity (45 min)", title: "The Ultimate Challenge", content: "Part 1 (10 min): Solve a puzzle — fastest time. Part 2 (10 min): Read a page aloud from any book. Part 3 (10 min): Create a 1-minute speech about anything. Part 4 (10 min): Play 1 game of chess. Part 5 (5 min): Do 1 experiment or building challenge." },
          { type: "THINK", label: "Thinking Questions", title: "Reflection Questions", qs: ["Which part was easiest — why? Was it always easy?", "Which part was hardest — why?", "What have you gotten better at this month?", "What would you do differently if you started again?"] },
          { type: "EXPRESS", label: "Expression", title: "Champion Speech", say: "Give me a 1-minute speech. Tell me: what you did this month, what you learned, and what you want to learn next. Stand up. Use the microphone. Speak to the whole family." },
          { type: "CLOSE", label: "Close", title: "Reinforce", say: "You used every skill. You proved to yourself that you can think, build, speak, and create. THAT is intelligence." },
        ],
      },
      {
        num: 30, title: "🎉 Celebration Day!", theme: "Reflection + Reward",
        objective: "Self-Reflection + Gratitude + Forward Planning",
        tags: ["Celebration", "Reflection", "Achievement"],
        tools: ["🎂 Special food/treat", "📜 Achievement certificate (draw one!)", "🎁 His chosen reward", "📸 Family photo"],
        prep: {
          items: [
            "Write the Achievement Certificate by hand the night before — make it detailed and personal",
            "Prepare his special treat or plan the celebration outing",
            "Collect ALL his work from 30 days: drawings, plant, inventions, observation diary — display them",
            "Take photos of his work and create a small display on the wall or table",
            "Buy or prepare a small gift if you planned a reward — keep it wrapped and hidden",
            "Write him a personal letter (even 5 lines) about what you observed him becoming this month",
          ],
          mindset: "Today is not about what he learned. It is about who he became. Tell him that. Look him in the eyes and say it. This memory will stay with him far longer than any activity you did.",
        },
        steps: [
          { type: "HOOK", label: "Hook", title: "Set the scene", say: "Today is YOUR day. You did something most children will never do — you worked on your mind for 30 straight days. Let's celebrate and look back at your journey." },
          { type: "ACTIVITY", label: "Activity", title: "The Big Review + Celebration", content: "Morning: Review his observation diary, plant growth, best creations. Make a 'Best of Manvay' display. Afternoon: Family celebration meal or outing. Evening: Certificate ceremony — read it out loud!" },
          { type: "THINK", label: "Reflection Questions", title: "Journey Questions", qs: ["What was your absolute favourite day — why?", "What was the hardest thing you did this month?", "What are you most proud of?", "What do you want to learn or do next?"] },
          { type: "EXPRESS", label: "Expression", title: "Final Reflection Speech", say: "Tell the whole family about your Summer Intelligence journey. What you did, what you learned, and what you want to do next. This is YOUR speech — make it proud." },
          { type: "CLOSE", label: "Close", title: "The Final Message", say: "You grew smarter because you showed up every single day. Intelligence is not a gift — it is built. And you built yours this summer. I am proud of you, Manvay." },
        ],
      },
    ],
  },
];

export const weeklyRotation = [
  { day: "Monday", emoji: "🔵", theme: "Science + Experiment", color: "#DBEAFE", textColor: "#1D4ED8", items: ["Active: Experiment (volcano, magnet, water)", "Brain: Puzzle", "Creative: Draw the experiment", "Real-life: Kitchen science observation"] },
  { day: "Tuesday", emoji: "🟢", theme: "Logic + Problem Solving", color: "#DCFCE7", textColor: "#15803D", items: ["Active: Build something", "Brain: Chess", "Creative: Improve design", "Real-life: Sorting / classifying"] },
  { day: "Wednesday", emoji: "🟡", theme: "Creativity + Expression", color: "#FEF3C7", textColor: "#B45309", items: ["Active: Role play / drama", "Brain: Pattern game", "Creative: Drawing + story", "Speaking: Full storytelling"] },
  { day: "Thursday", emoji: "🔴", theme: "Real World Learning", color: "#FFE4E6", textColor: "#BE123C", items: ["Active: Cooking / helping at home", "Brain: Memory game", "Creative: Explain the steps", "Real-life: Life skills practice"] },
  { day: "Friday", emoji: "🟣", theme: "Thinking + WHY Day", color: "#EDE9FE", textColor: "#6D28D9", items: ["Active: Observation walk", "Brain: Harder puzzle challenge", "Speaking: 10 WHY questions", "Reading: Chapter discussion"] },
  { day: "Saturday", emoji: "🟠", theme: "Project Day", color: "#FFEDD5", textColor: "#C2410C", items: ["Week 1: Plant Growing 🌱", "Week 2: Bridge engineering", "Week 3: Mini city build", "Week 4: Invention from waste"] },
  { day: "Sunday", emoji: "🎉", theme: "Fun + Family Review", color: "#CCFBF1", textColor: "#0F766E", items: ["Games + outdoor + family time", "Ask: 'What was your best moment this week?'", "Ask: 'What was hardest? What did you learn?'", "Plan next week together with him"] },
];
